# Generated by Django 5.0.1 on 2024-01-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
