# Generated by Django 5.0.1 on 2024-02-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ("collection1")
        """,
            """
            DELETE FROM store_collection
            WHERE title="collection1"
        """,
        )
    ]
